import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { VContainer } from '../layouts'
import styles from '../styles/views/Home.module.scss'

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Erick Escriba Arango</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/logo.svg" />
      </Head>
      <h1>
        <Image src="/logos/logo.svg" alt="Erick Logo" width={34} height={34} />
      </h1>

      <div className={styles.Home__background}>
        <VContainer>
          <div className={styles.Home__container}>
            <h2 className={styles.Home__body__brand}>Hi, my name is</h2>
            <h2 className={styles.Home__heading}>Erick Escriba.</h2>
            <h2 className={styles.Home__heading}>I build things for the web.</h2>
            <p className={styles.Home__body}>
              I'm a front-end developer based in Lima, Peru . I'm currently into Web Development and
              I'm passionate in building exceptional websites
            </p>
            <button className={styles.Home__button}>
              {/* <Link href="mailto:erickescribaa@gmail.com"> */}
              <a href="mailto:erickescribaa@gmail.com" target="_blank">Get in touch</a>
              {/* </Link> */}
            </button>
          </div>
        </VContainer>
      </div>
    </>
  )
}
export default Home
