import { NextPage } from 'next'
import Head from 'next/head'

import { VContainer, VMenu } from '../layouts'
import { IAbout, IExperience, IHome, IContact, IEmail, ISocial } from '../widgets'

import styles from '../styles/views/Home.module.scss'
import React from 'react'

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Erick Escriba Arango</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/logo.svg" />
      </Head>
      <VMenu />
      <IEmail />
      <ISocial />
      <div className={styles.Home__banner}>
        <VContainer>
          <IHome />
        </VContainer>
      </div>

      <div className={styles.Home__about} id="about">
        <VContainer>
          <IAbout />
        </VContainer>
      </div>
      <div className={styles.Home__experience} id="experience">
        <VContainer>
          <IExperience />
        </VContainer>
      </div>

      <div className={styles.Home__contact} id="contact">
        <VContainer>
          <IContact />
        </VContainer>
      </div>
    </>
  )
}
export default Home
